### ISSUE TITLE
Resolving Play-By-Play with Game Feed

### ISSUE THREAD

**Issue by jangerhofer** [sfrechette/nhlplaybyplay-node#1]
Hello!  I found this project through your [blog post](http://stephanefrechette.com/fetching-nhl-play-play-game-data/#.WFcVUHeZNAg) (which I found via Google!) while trying to resolve a question I have about the NHL Stats API.  I am wondering whether you have any idea what is at work here...

As far I can tell, there are two separate API endpoints which contain play-by-play data.  The first is the one you highlighted in this project, which looks like: http://live.nhl.com/GameData/20162017/2016020471/PlayByPlay.json. The other feed powers the "ice tracker" view that is part rink-graphic, part boxscore; https://statsapi.web.nhl.com/api/v1/game/2016020471/feed/live.  Comparing the two, two things are immediately evident to me:

1. The latter /feed/live returns many more events in total.  Some of those events are relatively useless (I've seen "Period End" followed by a new event, "Official Period End"), but nonetheless there are one the order of three times as many events in total as there are in the first feed.
2. The /feed/live does NOT include data about which players were on the ice (but not directly involved in the play) for each play.  

At some point in the near future, I'll investigate further and put together a better comparison.  I am just wondering whether you have seen this alternative feed and/or have any thoughts about how complete this project's current endpoint is!

**Comment by sfrechette** [comment]
Hi JD thanks for the input. I was aware of the second feed, but decided that the first one was sufficient for my needs. The feed that I am using also contains the play by play coordinates for each plays (X,Y). To help you decipher the JSON from the second feed I recommend a tool like the "Cocoa JSON Editor". Bottom line is that he second feed is more complete, but with lots of 'junk' and redundant information...

**Comment by jangerhofer** [comment]
Awesome, thanks for the guidance!  It's weird that there isn't one combined feed -- I understand varying the level of detail, but putting some information in one feed (e.g. coordinates on the ice) but not the other is less than helpful.  I suppose that at the end of the day, the feeds are only intended for NHL applications rather than for outside developers -- a shame!  

Cheers!
